const VITE_OPEN_WEATHER_MAP_API_KEY = import.meta.env
  .VITE_OPEN_WEATHER_MAP_API_KEY;
 const VITE_WEATHER_API_KEY = import.meta.env.VITE_WEATHER_API_KEY;


export { VITE_OPEN_WEATHER_MAP_API_KEY, VITE_WEATHER_API_KEY };
